#! /usr/bin/env python2

from sys import path
path.append("lib")

import hosts

inv = hosts.Inventory('site/site.conf',
  ipv6_local_network = "fd2f:5119:f2c::/64",
  icvpn_ipv4_network = "10.207.0.196/16",
  icvpn_ipv6_network = "fec0::a:cf:0:c4/96",
)

grp = inv.group("vpnservers",
  dhcp=True,
  icvpn=True,
  batman_gateway=True,
  alfred_master=True,
)
grp.host(9, "test.bremen.freifunk.net")

print inv.json_dump(indent=4)
