---
babeld_repository: "https://dl.ffm.freifunk.net/debian-packages/ sid main"
babeld_repository_key: 390BF305

babel_interface: babel-{{ site_code }}
vpn_interface: vpn-{{ site_code }}-babel
babel_mmfd_prefix: "ff05::/64"
