---
- hosts: vpnservers
  vars:
    batman_gateway: true
  roles:
  - apt
  - openssh
  - batman-adv-14
  - main-bridge
  - role: fastd
    tags: fastd
  - role: babeld
    tags: babel
  - role: mmfd
    tags: babel
  - role: l3roamd
    tags: babel
  - alfred-announce-cleanup
  - mesh-announce
  - backbone-gre
  - icvpn
  - exit-ipv4
  - exit-ipv6
  - chrony
  - unbound
  - dnsmasq
  - system
  - tmpfs
  - tools
  - motd
