- name: Add repository key for babeld and utils
  apt_key: keyserver="{{ pgp_keyserver }}" id="{{babeld_repository_key}}"

- name: Add repository for babeld and utils
  apt_repository: repo="deb {{babeld_repository}}"

- name: Install babel utils
  apt: name="{{item}}"
  with_items:
  - babeld
  - l3roamd
  - mmfd

- name: Upload babeld.conf
  template: src=babeld.conf dest=/etc/babeld.conf
  notify:
  - restart babeld

- name: Install interfaces file
  template: >
    src=interfaces
    dest=/etc/network/interfaces.d/babeld-{{site_code}}

- name: Configure firewall
  template: src=firewall.sh dest={{ firewall_path }}/30-babeld
  when: firewall_enabled
  notify: reload firewall

- name: Install babeld service
  template: src=babeld.service dest=/etc/systemd/system/babeld.service
  notify:
  - reload systemd
  - restart babeld

- name: Install l3roamd service
  template: src=l3roamd.service dest=/etc/systemd/system/l3roamd.service
  notify:
  - reload systemd
  - restart l3roamd

- name: Install mmfd service
  template: src=mmfd.service dest=/etc/systemd/system/mmfd.service
  notify:
  - reload systemd
  - restart mmfd

- name: Copy echotobabel
  copy: src=echotobabel dest=/usr/local/bin/echotobabel

- name: Set interfaces up
  command: ifup {{ item }}
  register: ifup_result
  changed_when: '"already configured" not in ifup_result.stderr'
  with_items:
  - "{{ babel_interface }}"
